---

- name: Ensure restic
  ansible.builtin.apt:
    name:
      - fuse3
      - restic
    state: present

- name: Ensure restic configuration directory
  ansible.builtin.file:
    path: /etc/ansible-restic
    state: directory
    mode: "0o700"

- name: Ensure restic service unit
  ansible.builtin.template:
    src: "restic@.service.j2"
    dest: "/etc/systemd/system/ansible-restic@.service"
    mode: "0o644"
  notify: Daemon reload

- name: Ensure syslog configuration
  ansible.builtin.template:
    src: restic-syslog.conf.j2
    dest: /etc/syslog-ng/conf.d/ansible-restic.conf
    mode: "0o644"
  notify: Restart syslog

- name: Include restic tasks
  ansible.builtin.include_tasks: "restic.yml"
  loop_control:
    loop_var: restic_job
  loop: "{{ restic_jobs }}"
