---

- name: Enable restic timer
  ansible.builtin.systemd:
    name: "ansible-restic-{{ restic_vars.name }}.timer"
    state: started
    enabled: true

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
